<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Francisca Apablaza">

<title>Trabajo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Participacion en el mercado laboral_files/libs/clipboard/clipboard.min.js"></script>
<script src="Participacion en el mercado laboral_files/libs/quarto-html/quarto.js"></script>
<script src="Participacion en el mercado laboral_files/libs/quarto-html/popper.min.js"></script>
<script src="Participacion en el mercado laboral_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Participacion en el mercado laboral_files/libs/quarto-html/anchor.min.js"></script>
<link href="Participacion en el mercado laboral_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Participacion en el mercado laboral_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Participacion en el mercado laboral_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Participacion en el mercado laboral_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Participacion en el mercado laboral_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Francisca Apablaza </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="participación-en-el-mercado-laboral" class="level1">
<h1>Participación en el mercado laboral</h1>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>La economía de un país es fundamental para su desarrollo y crecimiento. En Chile, la participación laboral es un tema recurrente en discursos políticos y discusiones económicas. Los políticos suelen utilizar indicadores como el índice de desempleo y la tasa de participación laboral para demostrar que tan bien o mal prospera y se encuentra la estabilidad económica del país. Es por esto que resulta de suma importancia analizar y entender los factores que influyen en la participación laboral de las personas en Chile. En este estudio, me enfocare en identificar y analizar los elementos que pueden afectar la participación laboral, desde la educación y la formación laboral hasta las condiciones laborales y la estructura económica del país. Al entender mejor estos factores, podemos desarrollar estrategias más efectivas para fomentar la integración laboral y mejorar las condiciones de trabajo en Chile. <span class="citation" data-cites="neffaTrabajoCrisisModelos2020">(<a href="#ref-neffaTrabajoCrisisModelos2020" role="doc-biblioref">Neffa and De La Garza Toledo 2020</a>)</span></p>
<p>Para poder adentrarme en el análisis del mercado laboral chileno, es importante primero realizar una contextualización histórica, sobre que sistema económico tenemos en Chile. Desde la década de 1970, en dictadura se impuso el modelo neoliberal en el país. Como nos dice Carrasco “Es un proceso que tiene antecedentes en las ideas del liberalismo económico, donde destaca la figura de Adam Smith y sus teorías sobre el mercado y el libre comercio, el laissez faire, la libertad e interés individual, la necesidad de la propiedad privada, el rol prescindente del Estado en las dinámicas económicas, entre otras que son la base de la economía clásica”. Esto nos ayuda a comprender bajo que ideas se ha desarrollado el mercado laboral chileno.</p>
<p>El neoliberalismo ha traído tanto dificultades como desigualdades bajo un discurso de progreso económico, hay ciertos puntos que nos puedes develar que factores influyen en la participación dentro del mercado laboral, algunos son factores como el género, el nivel educación, las condiciones laborales, etc. Estos algunos de desafíos a los que nos enfrentamos para mejorar, la participación y la calidad del mercado laboral.</p>
<p>Para realizar este análisis estaré trabajando con la Encuesta de Caracterización social (CASEN), del año 2022, la cual es una encuesta hacia los hogares realizado por el Ministerio de Desarrollo Social y Familia. La cual recodifique antes de los resultados que se presentaran en este trabajao, ya que la base de datos es muy pesada, filtre por solo las variables que necesitare trabajar a lo largo de esta investigacion.</p>
</section>
<section id="trabajo-en-rstudio" class="level2">
<h2 class="anchored" data-anchor-id="trabajo-en-rstudio">Trabajo en Rstudio</h2>
<p>A lo largo de esta investigación, he trabajado con cuatro scripts con el objetivo de mantener el orden y para llevar a cabo distintos análisis de las variables. A partir de aquí, presentaré el desarrollo realizado en cada uno de estos scripts, junto con sus resultados, análisis y conclusiones. Todo con el objetivo de realizar un análisis de la participación en el mercado laboral en Chile.</p>
<section id="cargar-paquetes" class="level4">
<h4 class="anchored" data-anchor-id="cargar-paquetes">Cargar paquetes:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sjlabelled, dplyr, stargazer, sjmisc, summarytools, kableExtra, sjPlot, corrplot, sessioninfo, ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cargar-base-de-datos" class="level4">
<h4 class="anchored" data-anchor-id="cargar-base-de-datos">Cargar base de datos:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://github.com/panchamama/Practico-1/raw/main/1.%20input/casen_rec.rdata"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Recodificamos la base de datos por edad entre 15 hasta 65 años, ya que considero este grupo etario como el optimo para participar dentro del mercado laboral.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>casen_rec <span class="ot">&lt;-</span> casen_rec <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span> <span class="fu">filter</span>(edad <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">65</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(casen_rec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 127700     14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(casen_rec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "edad"              "sexo"              "educ"             
 [4] "trabajo"           "trabajo_informal"  "busqueda_trabajo" 
 [7] "horas_trabajo"     "tipo_trabajo"      "contrato"         
[10] "jornada_labora"    "horario_trabajo"   "sueldo"           
[13] "nacionalidad"      "pueblo_originario"</code></pre>
</div>
</div>
<p>Vemos los primeros descriptivos que nos ofrece la base datos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(casen_rec,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>,<span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>))<span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">kable</span>(.,<span class="st">"markdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">edad</td>
<td style="text-align: left;">Edad</td>
<td style="text-align: right;">127700</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">41.0188645</td>
<td style="text-align: right;">14.0305535</td>
<td style="text-align: left;">47 (18-65)</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">sexo</td>
<td style="text-align: left;">sexo</td>
<td style="text-align: right;">127700</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.4683242</td>
<td style="text-align: right;">0.4989976</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">educ</td>
<td style="text-align: left;">educ</td>
<td style="text-align: right;">112246</td>
<td style="text-align: right;">12.10180</td>
<td style="text-align: right;">3.1026406</td>
<td style="text-align: right;">0.7505976</td>
<td style="text-align: left;">4 (1-5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">13</td>
<td style="text-align: left;">trabajo</td>
<td style="text-align: left;">trabajo</td>
<td style="text-align: right;">127700</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.5927095</td>
<td style="text-align: right;">0.4913317</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14</td>
<td style="text-align: left;">trabajo_informal</td>
<td style="text-align: left;">trabajo_informal</td>
<td style="text-align: right;">52011</td>
<td style="text-align: right;">59.27095</td>
<td style="text-align: right;">1.0331276</td>
<td style="text-align: right;">0.1789715</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">busqueda_trabajo</td>
<td style="text-align: left;">busqueda_trabajo</td>
<td style="text-align: right;">38955</td>
<td style="text-align: right;">69.49491</td>
<td style="text-align: right;">1.3863432</td>
<td style="text-align: right;">0.4869171</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">horas_trabajo</td>
<td style="text-align: left;">horas_trabajo</td>
<td style="text-align: right;">79529</td>
<td style="text-align: right;">37.72200</td>
<td style="text-align: right;">2.7104327</td>
<td style="text-align: right;">0.6019090</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">tipo_trabajo</td>
<td style="text-align: left;">tipo_trabajo</td>
<td style="text-align: right;">80407</td>
<td style="text-align: right;">37.03446</td>
<td style="text-align: right;">0.8256060</td>
<td style="text-align: right;">0.3279793</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">contrato</td>
<td style="text-align: left;">contrato</td>
<td style="text-align: right;">58586</td>
<td style="text-align: right;">54.12216</td>
<td style="text-align: right;">0.8594374</td>
<td style="text-align: right;">0.3440683</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">jornada_labora</td>
<td style="text-align: left;">jornada_labora</td>
<td style="text-align: right;">58803</td>
<td style="text-align: right;">53.95223</td>
<td style="text-align: right;">0.9154210</td>
<td style="text-align: right;">0.2096932</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">horario_trabajo</td>
<td style="text-align: left;">horario_trabajo</td>
<td style="text-align: right;">58946</td>
<td style="text-align: right;">53.84025</td>
<td style="text-align: right;">0.8040155</td>
<td style="text-align: right;">0.3910666</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;">sueldo</td>
<td style="text-align: left;">sueldo</td>
<td style="text-align: right;">57505</td>
<td style="text-align: right;">54.96868</td>
<td style="text-align: right;">1.6330232</td>
<td style="text-align: right;">0.6965349</td>
<td style="text-align: left;">2 (1-3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">nacionalidad</td>
<td style="text-align: left;">nacionalidad</td>
<td style="text-align: right;">127700</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.0666406</td>
<td style="text-align: right;">0.2493995</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;">pueblo_originario</td>
<td style="text-align: left;">pueblo_originario</td>
<td style="text-align: right;">127700</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">1.1374236</td>
<td style="text-align: right;">0.3442954</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="analisis-de-variables" class="level3">
<h3 class="anchored" data-anchor-id="analisis-de-variables">Analisis de variables</h3>
<p>Lo primero que realizare es una asociación entre algunas variable y cruzadas con la variable de sexo esto para tener una primera visualización de la participación laboral</p>
<p>a) Realizo trabajo formal</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(casen_rec<span class="sc">$</span>trabajo, casen_rec<span class="sc">$</span>sexo,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.col.prc=</span><span class="cn">TRUE</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.summary=</span><span class="cn">FALSE</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">encoding =</span> <span class="st">"UTF-8"</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">trabajo</td>
<td colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">sexo</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mujer</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Hombre</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">No trabaja</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">34900</span><br>
<span style="color:#339933;">51.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">17111</span><br>
<span style="color:#339933;">28.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">52011</span><br>
<span style="color:#339933;">40.7&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Trabaja</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">32995</span><br>
<span style="color:#339933;">48.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">42694</span><br>
<span style="color:#339933;">71.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">75689</span><br>
<span style="color:#339933;">59.3&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">67895</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">59805</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">127700</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Esta primera tabla nos ofrece lo siguiente, la cantidad de personas que realizan trabajo formal, son más hombres que mujeres, siendo los hombres un 71.4%, mientras que las mujeres son el 48.6%. Cuando vemos quienes no hay realizado un trabajo formal vemos que son la mayoría mujeres siendo un 51.4% mientras que los hombres son un 28.6%, esto es un primer acercamiento a las brechas de género que experimenta el mercado laboral.</p>
<p>b) Realizo algun trabajo de manera informal</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(casen_rec<span class="sc">$</span>trabajo_informal, casen_rec<span class="sc">$</span>sexo,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.col.prc=</span><span class="cn">TRUE</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.summary=</span><span class="cn">FALSE</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">encoding =</span> <span class="st">"UTF-8"</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">trabajo_informal</td>
<td colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">sexo</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mujer</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Hombre</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">No trabaja</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">33913</span><br>
<span style="color:#339933;">97.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">16375</span><br>
<span style="color:#339933;">95.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">50288</span><br>
<span style="color:#339933;">96.7&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Trabaja</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">987</span><br>
<span style="color:#339933;">2.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">736</span><br>
<span style="color:#339933;">4.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">1723</span><br>
<span style="color:#339933;">3.3&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">34900</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">17111</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">52011</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Ahora bien, la pregunta iba a si realizo algún trabajo por salario sin necesidad que este fuera formal. Los resultados no son tan demostrativos ya que la mayoría tanto hombres como mujeres no han trabajado de manera informal y nos quedamos con muy pocos casos de quienes si lo han realizado. Sim embargo quienes si lo han hecho son más mujeres siendo 987, mientras que los hombres son 736 personas.</p>
<p>c) Cuantas horas trabajo a la semana</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(casen_rec<span class="sc">$</span>horas_trabajo, casen_rec<span class="sc">$</span>sexo,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.col.prc=</span><span class="cn">TRUE</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.summary=</span><span class="cn">FALSE</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">encoding =</span> <span class="st">"UTF-8"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">horas_trabajo</td>
<td colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">sexo</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mujer</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Hombre</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Inf promedio</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4016</span><br>
<span style="color:#339933;">11.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2210</span><br>
<span style="color:#339933;">5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6226</span><br>
<span style="color:#339933;">7.8&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Promedio</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6320</span><br>
<span style="color:#339933;">17.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4257</span><br>
<span style="color:#339933;">9.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">10577</span><br>
<span style="color:#339933;">13.3&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Sup promedio</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">25292</span><br>
<span style="color:#339933;">71&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">37434</span><br>
<span style="color:#339933;">85.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">62726</span><br>
<span style="color:#339933;">78.9&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">35628</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">43901</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">79529</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En la siguiente tabla se pregunta por la cantidad de horas que ha trabajado una persona. De lo cual se observa lo siguiente: Las horas promedio de trabajo son más mujeres (17.7%) que hombres (9.7%), que lo realizan, sin embargo, cuando analizamos trabajar horas inferiores al promedio y trabajar superiores al promedio, vemos que en el primer punto son más mujeres quienes traban menos horas habituales al promedio, y a su inversa cuando vemos quienes son los que más trabajan sobre el promedio son los hombres. Esto quiere decir que las mujeres trabajen menos, no necesariamente.</p>
<p>d) Razonas por la cual no busco trabajo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(casen_rec<span class="sc">$</span>busqueda_trabajo, casen_rec<span class="sc">$</span>sexo,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.col.prc=</span><span class="cn">TRUE</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.summary=</span><span class="cn">FALSE</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">encoding =</span> <span class="st">"UTF-8"</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">busqueda_trabajo</td>
<td colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">sexo</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mujer</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Hombre</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Otro motivo</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">13454</span><br>
<span style="color:#339933;">48.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">10451</span><br>
<span style="color:#339933;">93.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">23905</span><br>
<span style="color:#339933;">61.4&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Razones de cuidado</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">14331</span><br>
<span style="color:#339933;">51.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">719</span><br>
<span style="color:#339933;">6.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">15050</span><br>
<span style="color:#339933;">38.6&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">27785</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">11170</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">38955</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Esta tabla es bien interesante, ya que responden las personas que no trabajan, a porque no han podido o querido buscar un trabajo, dentro de las opciones agrupe todas las que referían al cuidado de algún familiar, niño, etc. y cuidado doméstico, toda cualquier otra razón la agrupe en otro motivo. El resultado de esto se ve en la tabla, de la cual podemos debelar que, si nos fijamos en la opción de razones de cuidado, vemos una amplia diferencia entre hombres y mujeres, donde solo un 6.4% de hombres no buscaron trabajo por razones de cuidado, mientras que las mujeres fueron un 51.6%, observamos una amplía diferencia. Esta tabla nos podría acercar a una interpretación de las tablas anteriores talvez las mujeres trabajan menos horas formales, pero se encuentran realizando otras labores que no siempre se cuentan como trabajo.</p>
<p>e) Sueldo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sjt.xtab</span>(casen_rec<span class="sc">$</span>sueldo, casen_rec<span class="sc">$</span>sexo,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.col.prc=</span><span class="cn">TRUE</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">show.summary=</span><span class="cn">FALSE</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">encoding =</span> <span class="st">"UTF-8"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">sueldo</td>
<td colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">sexo</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mujer</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Hombre</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Menos del salario<br>
minimo</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">14994</span><br>
<span style="color:#339933;">57&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">13379</span><br>
<span style="color:#339933;">42.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">28373</span><br>
<span style="color:#339933;">49.3&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Salario promedio</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">8474</span><br>
<span style="color:#339933;">32.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">13388</span><br>
<span style="color:#339933;">42.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">21862</span><br>
<span style="color:#339933;">38&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Salario sobre el<br>
promedio</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2826</span><br>
<span style="color:#339933;">10.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4444</span><br>
<span style="color:#339933;">14.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">7270</span><br>
<span style="color:#339933;">12.6&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">26294</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">31211</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double;"><span style="color:black;">57505</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Por último, temeos esta taba sobre el sueldo mensual de una persona, cruzada con la variable sexo. Obteniendo los siguiente: Si vemos las personas que ganan menos del salario mínimo, vemos que son más mujeres quienes se encuentran ahí, es más si vemos el grupo de las mujeres, la mayoría está concentrada en este punto. Mientras que los hombres están más o menos igualmente divididos entre menos del salario mínimo y el salario promedio. Ahora bien, si nos situamos en el salario promedio las mujeres son 32.2% mientras que los hombres son el 42.9% una diferencia del 10%. Y por último cuando vemos quienes ganan sobre el salario mínimo vemos que son más hombre siendo 14.2% y las mujeres un 10.7%.</p>
<p>Esta tabla es muy rica en informacion, sin embargo no podemos afirmar en su totalidad que las mujeres ganan menos que los hombres, ya que analizamos solo una muestra,pero, nos ayuda a plantear otras interrogantes y debelar desigualdades salariales que hay que estudiar.</p>
</section>
<section id="correlación-entre-variables" class="level3">
<h3 class="anchored" data-anchor-id="correlación-entre-variables">Correlación entre variables</h3>
<p>Ahora limpiamos el area de trabajo para cargar los datos que nos permitiran realizar la correlación.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co">#limpiar area de trabajo</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, <span class="co"># Manipulacion datos</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>               sjmisc, <span class="co"># Descriptivos</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>               sjPlot, <span class="co"># Tablas</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>               sjlabelled, <span class="co">#etiquetas</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>               kableExtra, <span class="co">#Tablas</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>               GGally, <span class="co"># Correlaciones</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>               corrplot) <span class="co"># Correlaciones</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># para desactivar notacion cientifica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cargamos nuevamente la base de datos y recodificamos por edad entre 15 y 65 años</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://github.com/panchamama/Practico-1/raw/main/1.%20input/casen_rec.rdata"</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>casen_rec <span class="ot">&lt;-</span> casen_rec <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span> <span class="fu">filter</span>(edad <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">65</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(casen_rec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 127700     14</code></pre>
</div>
</div>
<p>Y ahora recodificamos un par de variables que anteriormente estábamos analizando como categóricas, pero, es necesario transformarlas en numéricas. Esto es realizado con el objetivo de poder realizar la correlación en de estas variables, para posteriormente realizar la escala.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(casen_rec<span class="sc">$</span>trabajo) <span class="co"># Recodificacion numerica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=127700 valid N=127700 mean=1.59 sd=0.49

Value      |     N | Raw % | Valid % | Cum. %
---------------------------------------------
No trabaja | 52011 | 40.73 |   40.73 |  40.73
Trabaja    | 75689 | 59.27 |   59.27 | 100.00
&lt;NA&gt;       |     0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>casen_rec<span class="sc">$</span>trabajo <span class="ot">&lt;-</span> <span class="fu">recode</span>(casen_rec<span class="sc">$</span>trabajo, <span class="st">"No trabaja"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"Trabaja"</span> <span class="ot">=</span> <span class="dv">1</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(casen_rec<span class="sc">$</span>trabajo) <span class="co">#Confirmacion</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  1.0000  0.5927  1.0000  1.0000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(casen_rec<span class="sc">$</span>trabajo_informal) <span class="co"># Recodificacion numerica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=127700 valid N=52011 mean=1.03 sd=0.18

Value      |     N | Raw % | Valid % | Cum. %
---------------------------------------------
No trabaja | 50288 | 39.38 |   96.69 |  96.69
Trabaja    |  1723 |  1.35 |    3.31 | 100.00
&lt;NA&gt;       | 75689 | 59.27 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>casen_rec<span class="sc">$</span>trabajo_informal <span class="ot">&lt;-</span> <span class="fu">recode</span>(casen_rec<span class="sc">$</span>trabajo_informal, <span class="st">"No trabaja"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"Trabaja"</span> <span class="ot">=</span> <span class="dv">1</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(casen_rec<span class="sc">$</span>trabajo_informal) <span class="co">#Confirmacion</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   0.00    0.00    0.00    0.03    0.00    1.00   75689 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(casen_rec<span class="sc">$</span>horas_trabajo) <span class="co"># Recodificacion numerica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=127700 valid N=79529 mean=2.71 sd=0.60

Value        |     N | Raw % | Valid % | Cum. %
-----------------------------------------------
Inf promedio |  6226 |  4.88 |    7.83 |   7.83
Promedio     | 10577 |  8.28 |   13.30 |  21.13
Sup promedio | 62726 | 49.12 |   78.87 | 100.00
&lt;NA&gt;         | 48171 | 37.72 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>casen_rec<span class="sc">$</span>horas_trabajo <span class="ot">&lt;-</span> <span class="fu">recode</span>(casen_rec<span class="sc">$</span>horas_trabajo, <span class="st">"Inf promedio"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"Promedio"</span> <span class="ot">=</span> <span class="fl">0.5</span>, <span class="st">"Sup promedio"</span> <span class="ot">=</span> <span class="dv">1</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(casen_rec<span class="sc">$</span>horas_trabajo) <span class="co">#Confirmacion</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   0.00    1.00    1.00    0.86    1.00    1.00   48171 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(casen_rec<span class="sc">$</span>sueldo) <span class="co"># Recodificacion numerica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=127700 valid N=57505 mean=1.63 sd=0.70

Value                     |     N | Raw % | Valid % | Cum. %
------------------------------------------------------------
Menos del salario minimo  | 28373 | 22.22 |   49.34 |  49.34
Salario promedio          | 21862 | 17.12 |   38.02 |  87.36
Salario sobre el promedio |  7270 |  5.69 |   12.64 | 100.00
&lt;NA&gt;                      | 70195 | 54.97 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>casen_rec<span class="sc">$</span>sueldo<span class="ot">&lt;-</span> <span class="fu">recode</span>(casen_rec<span class="sc">$</span>sueldo, <span class="st">"Menos del salario minimo"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"Salario promedio"</span> <span class="ot">=</span> <span class="fl">0.5</span>, <span class="st">"Salario sobre el promedio"</span> <span class="ot">=</span> <span class="dv">1</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(casen_rec<span class="sc">$</span>sueldo) <span class="co">#Confirmacion</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   0.00    0.00    0.50    0.32    0.50    1.00   70195 </code></pre>
</div>
</div>
<p>Para la correlacio}ón realice un objeto con solo las variables necesarias para esta correlación</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>casen_correlacion <span class="ot">&lt;-</span> casen_rec <span class="sc">%&gt;%</span> <span class="fu">select</span>(trabajo_informal, <span class="co"># Trabajo informal</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                                          horas_trabajo, <span class="co"># Horas trabajadas</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                                          tipo_trabajo, <span class="co"># Su trabajo es de tipo</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                                          contrato, <span class="co"># Tipo de contrato</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                                          jornada_labora, <span class="co">#Jornada laboral</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>                                          horario_trabajo, <span class="co">#Tipo de horario</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>                                          sueldo) <span class="co"># Sueldo</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="casos-perdidos-nas" class="level4">
<h4 class="anchored" data-anchor-id="casos-perdidos-nas">Casos perdidos (NA´s)</h4>
<p>Es importante trabajar los casos perdidos (NA´s), para que no alteren la correlación entre las variables, para esto he decidido realizar la filtración de los casos perdidos por “Listwise delectio” ya que a pesar de lo contrapuducente, es que realice ambas pruebas de eliminación de casos perdidos “Listwise” y “Pairwise”, y no había mucha diferencia en los resultados, por ende elegí la primera ya que era la que me estaba dando mejores resultados., para llevarlo a cabo el procedimiento es el siguiente:</p>
<ul>
<li>Primero respaldar la base de datos, en este caso el objeto para la correlacion</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> casen_correlacion</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(casen_correlacion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 127700      7</code></pre>
</div>
</div>
<ul>
<li>Despues contamos los NA´s</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(casen_correlacion))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 448113</code></pre>
</div>
</div>
<ul>
<li>Vemos en que variables se encuentran estos NA´s</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(casen_correlacion))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>trabajo_informal    horas_trabajo     tipo_trabajo         contrato 
           75689            48171            47293            69114 
  jornada_labora  horario_trabajo           sueldo 
           68897            68754            70195 </code></pre>
</div>
</div>
<ul>
<li>Y finalmente las eliminamos</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>casen_correlacion <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(casen_correlacion)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(casen_correlacion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3331    7</code></pre>
</div>
</div>
</section>
</section>
<section id="contruccion-de-matriz-de-correlacion" class="level3">
<h3 class="anchored" data-anchor-id="contruccion-de-matriz-de-correlacion">Contruccion de matriz de correlacion</h3>
<p>Acontinuacion una vez ya eliminados los NA´s, realizó la matriz de correlacion de las variables, para ver que tan correlacionadas estan unas variables con otras.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(casen_correlacion, <span class="at">use =</span> <span class="st">"complete.obs"</span>) <span class="co"># Matriz de correlacion</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>M</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 trabajo_informal horas_trabajo tipo_trabajo    contrato
trabajo_informal       1.00000000   -0.29755315  -0.38907112 -0.42005609
horas_trabajo         -0.29755315    1.00000000   0.39085097  0.45686696
tipo_trabajo          -0.38907112    0.39085097   1.00000000  0.57445354
contrato              -0.42005609    0.45686696   0.57445354  1.00000000
jornada_labora        -0.22980228    0.60550709   0.30691853  0.30699835
horario_trabajo        0.04073478   -0.05513761  -0.02356858 -0.03822644
sueldo                -0.12656961    0.21626158   0.23430805  0.23060927
                 jornada_labora horario_trabajo      sueldo
trabajo_informal     -0.2298023      0.04073478 -0.12656961
horas_trabajo         0.6055071     -0.05513761  0.21626158
tipo_trabajo          0.3069185     -0.02356858  0.23430805
contrato              0.3069984     -0.03822644  0.23060927
jornada_labora        1.0000000      0.13902757  0.12092705
horario_trabajo       0.1390276      1.00000000 -0.05437766
sueldo                0.1209270     -0.05437766  1.00000000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_corr</span>(M, <span class="co"># Visualizacion</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">triangle =</span> <span class="st">"lower"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">trabajo_informal</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">horas_trabajo</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">tipo_trabajo</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">contrato</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">jornada_labora</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">horario_trabajo</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">sueldo</td>
</tr>
<tr class="even">
<td style="font-style: italic">trabajo_informal</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">horas_trabajo</td>
<td style="text-align: center; padding: 0.2cm;">-0.298</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">tipo_trabajo</td>
<td style="text-align: center; padding: 0.2cm;">-0.389</td>
<td style="text-align: center; padding: 0.2cm;">0.391</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">contrato</td>
<td style="text-align: center; padding: 0.2cm;">-0.420</td>
<td style="text-align: center; padding: 0.2cm;">0.457</td>
<td style="text-align: center; padding: 0.2cm;">0.574</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">jornada_labora</td>
<td style="text-align: center; padding: 0.2cm;">-0.230</td>
<td style="text-align: center; padding: 0.2cm;">0.606</td>
<td style="text-align: center; padding: 0.2cm;">0.307</td>
<td style="text-align: center; padding: 0.2cm;">0.307</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">horario_trabajo</td>
<td style="text-align: center; padding: 0.2cm;">0.041</td>
<td style="text-align: center; padding: 0.2cm;">-0.055</td>
<td style="text-align: center; padding: 0.2cm;">-0.024</td>
<td style="text-align: center; padding: 0.2cm;">-0.038</td>
<td style="text-align: center; padding: 0.2cm;">0.139</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">sueldo</td>
<td style="text-align: center; padding: 0.2cm;">-0.127</td>
<td style="text-align: center; padding: 0.2cm;">0.216</td>
<td style="text-align: center; padding: 0.2cm;">0.234</td>
<td style="text-align: center; padding: 0.2cm;">0.231</td>
<td style="text-align: center; padding: 0.2cm;">0.121</td>
<td style="text-align: center; padding: 0.2cm;">-0.054</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td colspan="8" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with listwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Participacion-en-el-mercado-laboral_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La matriz de correlacion nos dice que tan correlacinada se esntunetran las variables</p>
</section>
<section id="alfa-de-cronbach" class="level3">
<h3 class="anchored" data-anchor-id="alfa-de-cronbach">Alfa de Cronbach</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de tener el paquete psych instalado y cargado</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"psych"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"psych"</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el alpha de Cronbach con la opción check.keys=TRUE</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>alpha_result <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(casen_correlacion, <span class="at">check.keys=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in psych::alpha(casen_correlacion, check.keys = TRUE): Some items were negatively correlated with the first principal component and were automatically reversed.
 This is indicated by a negative sign for the variable name.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver los resultados</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(alpha_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = casen_correlacion, check.keys = TRUE)

  raw_alpha std.alpha G6(smc) average_r  S/N    ase mean   sd median_r
      0.65      0.42    0.55     0.095 0.73 0.0092 0.69 0.19     0.12

    95% confidence boundaries 
         lower alpha upper
Feldt     0.63  0.65  0.67
Duhachek  0.63  0.65  0.67

 Reliability if an item is dropped:
                  raw_alpha std.alpha G6(smc) average_r  S/N alpha se var.r
trabajo_informal-      0.60      0.64    0.67     0.227 1.77   0.0108 0.048
horas_trabajo          0.57      0.22    0.35     0.045 0.28   0.0114 0.074
tipo_trabajo           0.57      0.28    0.42     0.060 0.38   0.0116 0.078
contrato               0.55      0.27    0.41     0.059 0.37   0.0123 0.072
jornada_labora         0.62      0.24    0.38     0.049 0.31   0.0102 0.089
horario_trabajo-       0.73      0.48    0.59     0.132 0.91   0.0073 0.117
sueldo                 0.65      0.38    0.54     0.091 0.60   0.0094 0.116
                   med.r
trabajo_informal-  0.231
horas_trabajo      0.041
tipo_trabajo       0.041
contrato           0.041
jornada_labora    -0.024
horario_trabajo-   0.231
sueldo             0.041

 Item statistics 
                     n raw.r std.r  r.cor r.drop mean   sd
trabajo_informal- 3331  0.64 -0.13 -0.490  0.409 0.82 0.39
horas_trabajo     3331  0.69  0.70  0.730  0.550 0.89 0.27
tipo_trabajo      3331  0.69  0.63  0.602  0.546 0.87 0.29
contrato          3331  0.73  0.64  0.627  0.573 0.87 0.34
jornada_labora    3331  0.52  0.68  0.674  0.360 0.89 0.24
horario_trabajo-  3331  0.33  0.30  0.025  0.029 0.19 0.39
sueldo            3331  0.50  0.49  0.286  0.259 0.29 0.35

Non missing response frequency for each item
                    0  0.5    1 miss
trabajo_informal 0.82 0.00 0.18    0
horas_trabajo    0.06 0.11 0.83    0
tipo_trabajo     0.07 0.12 0.81    0
contrato         0.13 0.01 0.86    0
jornada_labora   0.03 0.16 0.81    0
horario_trabajo  0.18 0.02 0.80    0
sueldo           0.54 0.34 0.12    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver cuáles variables fueron invertidas</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(alpha_result<span class="sc">$</span>keys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] "-trabajo_informal" "horas_trabajo"     "tipo_trabajo"     
[4] "contrato"          "jornada_labora"    "-horario_trabajo" 
[7] "sueldo"           </code></pre>
</div>
</div>
<p>Desarrollar esto en profuncidad, recordar que tuve que invertir las variables pero debo justificar por que</p>
</section>
<section id="contruccion-de-la-escala" class="level3">
<h3 class="anchored" data-anchor-id="contruccion-de-la-escala">Contruccion de la escala</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>casen_rec <span class="ot">&lt;-</span> casen_rec <span class="sc">%&gt;%</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">participacion_mercado_laboral =</span> <span class="fu">sum</span>(trabajo,trabajo_informal,horas_trabajo,tipo_trabajo,contrato,jornada_labora,horario_trabajo,sueldo))</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(casen_rec<span class="sc">$</span>participacion_mercado_laboral)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    0.5     4.5     5.0     4.8     5.5     7.0  124369 </code></pre>
</div>
</div>
<p>ddddddddddddddddddd</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(casen_rec<span class="sc">$</span>participacion_mercado_laboral)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=127700 valid N=3331 mean=4.80 sd=1.00

Value |      N | Raw % | Valid % | Cum. %
-----------------------------------------
 0.50 |      2 |  0.00 |    0.06 |   0.06
 1.00 |      5 |  0.00 |    0.15 |   0.21
 1.50 |     26 |  0.02 |    0.78 |   0.99
 2.00 |     43 |  0.03 |    1.29 |   2.28
 2.50 |     88 |  0.07 |    2.64 |   4.92
 3.00 |    120 |  0.09 |    3.60 |   8.53
 3.50 |    157 |  0.12 |    4.71 |  13.24
 4.00 |    372 |  0.29 |   11.17 |  24.41
 4.50 |    409 |  0.32 |   12.28 |  36.69
 5.00 |   1009 |  0.79 |   30.29 |  66.98
 5.50 |    640 |  0.50 |   19.21 |  86.19
 6.00 |    354 |  0.28 |   10.63 |  96.82
 6.50 |     88 |  0.07 |    2.64 |  99.46
 7.00 |     18 |  0.01 |    0.54 | 100.00
 &lt;NA&gt; | 124369 | 97.39 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>ddddddddddddddddddd</p>
<p>Grafico</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(casen_rec, <span class="fu">aes</span>(<span class="at">x =</span> participacion_mercado_laboral)) <span class="sc">+</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.6</span>, <span class="at">colour=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"yellow"</span>) <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Participacion en el mercado laboral"</span>) <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cantidad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 124369 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Participacion-en-el-mercado-laboral_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>blablablablabl</p>
<p>Antes de continuar es necesario guardar la base datos, para trabajar con las variables para la regresion con escala</p>
</section>
<section id="guardar-la-nueva-vase-de-datos-casen_reg" class="level3">
<h3 class="anchored" data-anchor-id="guardar-la-nueva-vase-de-datos-casen_reg">Guardar la nueva vase de datos (casen_reg)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>casen_reg <span class="ot">&lt;-</span> casen_rec <span class="sc">%&gt;%</span> <span class="fu">select</span>(participacion_mercado_laboral,</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>                                  sexo,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                                  educ,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                                  nacionalidad,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                                  pueblo_originario)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(casen_reg,<span class="at">file =</span> <span class="st">"1. input/casen_reg.rdata"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="regresion" class="level2">
<h2 class="anchored" data-anchor-id="regresion">Regresion</h2>
<p>Como ahora trabajare con otra base de datos es necesario limpiar el area de trabajo, cargar los paquetes necesarios, y asi continuar</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co">#limpiar area de trabajo</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr,</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>               car, </span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>               sjmisc, </span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>               sjPlot, </span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>               sjlabelled, </span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>               stargazer, </span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>               kableExtra, </span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>               corrplot, </span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>               texreg, </span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>               ggplot2, </span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>               ggpubr,</span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>               summarytools, <span class="co"># Tablas</span></span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>               sessioninfo, <span class="co"># Información de la sesión de trabajo</span></span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a>               fastDummies, <span class="co"># Generar regresión</span></span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a>               ggeffects) <span class="co"># Gráfico de valores predichos</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cargamos esta nueva base da datos recodificada con lo necesario para realizar la regresion</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://github.com/panchamama/Practico-1/raw/main/1.%20input/casen_reg.rdata"</span>))</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(casen_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 127700      5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>casen_reg <span class="ot">&lt;-</span> casen_reg <span class="sc">%&gt;%</span> <span class="fu">select</span>(participacion_mercado_laboral, sexo, educ, nacionalidad, pueblo_originario)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>ffffffffffff</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>casen_reg <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">lapply</span>(casen_reg, <span class="cf">function</span>(x) {</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.factor</span>(x)) <span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(x)) <span class="cf">else</span> x</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>}))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar solo las columnas numéricas</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>casen_reg_numeric <span class="ot">&lt;-</span> casen_reg[<span class="fu">sapply</span>(casen_reg, is.numeric)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la matriz de correlación utilizando solo las observaciones completas</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(casen_reg_numeric, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              participacion_mercado_laboral         sexo
participacion_mercado_laboral                    1.00000000 -0.032616616
sexo                                            -0.03261662  1.000000000
educ                                             0.24549661 -0.203797752
nacionalidad                                    -0.02998084 -0.023214915
pueblo_originario                               -0.03055307 -0.006051768
                                     educ nacionalidad pueblo_originario
participacion_mercado_laboral  0.24549661  -0.02998084      -0.030553069
sexo                          -0.20379775  -0.02321491      -0.006051768
educ                           1.00000000   0.01106689      -0.072294543
nacionalidad                   0.01106689   1.00000000      -0.030481152
pueblo_originario             -0.07229454  -0.03048115       1.000000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(casen_reg, <span class="at">use =</span> <span class="st">"complete.obs"</span>) <span class="co"># Usar solo casos con observaciones completas</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(M) <span class="ot">=</span> <span class="cn">NA</span> <span class="co"># Elimina la diagonal (correlaciones absolutas de cada variable consigmo misma)</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(M) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A. Participacion en el mescado laboral"</span>,</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"B. Sexo"</span>,</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"C. Educación"</span>,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"D. Nacionalidad"</span>,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"E. Pertenece a pueblo originario"</span>)</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(M) <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"(A)"</span>, <span class="st">"(B)"</span>,<span class="st">"(C)"</span>, <span class="st">"(D)"</span>, <span class="st">"(E)"</span>)</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>corrplot<span class="sc">::</span><span class="fu">corrplot</span>(M,</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">"color"</span>, <span class="co"># Cambia los círculos por color completo de cada cuadrante</span></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>                   <span class="at">addCoef.col =</span> <span class="st">"#000390"</span>, <span class="co"># Color de los coeficientes</span></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>                   <span class="at">type =</span> <span class="st">"upper"</span>, <span class="co"># Deja solo las correlaciones de arriba</span></span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="co"># COlor letras, rojo por defecto</span></span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>                   <span class="at">na.label =</span> <span class="st">"-"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Participacion-en-el-mercado-laboral_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>nos aseguramos ahora que todas las variables sean categoricas</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>casen_reg<span class="sc">$</span>educ <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(casen_reg<span class="sc">$</span>educ)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>casen_reg<span class="sc">$</span>sexo <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(casen_reg<span class="sc">$</span>sexo)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>casen_reg<span class="sc">$</span>nacionalidad <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(casen_reg<span class="sc">$</span>nacionalidad)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>casen_reg<span class="sc">$</span>pueblo_originario <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(casen_reg<span class="sc">$</span>pueblo_originario)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>y ahora realiizamos la regresion</p>
<section id="regrasion-1" class="level3">
<h3 class="anchored" data-anchor-id="regrasion-1">Regrasion 1</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>casen_reg <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(casen_reg)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_mercado_laboral <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>casen_reg)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg1, <span class="at">type=</span><span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=================================================
                         Dependent variable:     
                    -----------------------------
                    participacion_mercado_laboral
-------------------------------------------------
Constant                      4.829***           
                               (0.017)           
                                                 
-------------------------------------------------
Observations                    3,067            
R2                              0.000            
Adjusted R2                     0.000            
Residual Std. Error       0.962 (df = 3066)      
=================================================
Note:                 *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</section>
<section id="regresione-lineal-multiple" class="level3">
<h3 class="anchored" data-anchor-id="regresione-lineal-multiple">Regresione lineal multiple</h3>
<p>El objetivo de esto es realizar un analisis entre los distinros modelos, para evaluar la participacion en el mercado laboral, y asi ver ver que variables afectan esta participacion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_mercado_laboral <span class="sc">~</span> sexo, <span class="at">data =</span> casen_reg)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_mercado_laboral <span class="sc">~</span> sexo <span class="sc">+</span> educ, <span class="at">data =</span> casen_reg)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>reg4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_mercado_laboral <span class="sc">~</span> sexo <span class="sc">+</span> educ <span class="sc">+</span> nacionalidad, <span class="at">data =</span> casen_reg)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>reg5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(participacion_mercado_laboral <span class="sc">~</span> sexo <span class="sc">+</span> educ <span class="sc">+</span> nacionalidad <span class="sc">+</span> pueblo_originario, <span class="at">data =</span> casen_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">knitreg</span>(<span class="fu">list</span>(reg2, reg3, reg4, reg5), </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.model.names =</span> <span class="fu">c</span>(<span class="st">"Modelo 1"</span>,</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Modelo 2"</span>,</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Modelo 3"</span>,</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Modelo 4"</span>),</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.note =</span> <span class="st">"*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05"</span>,</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.coef.names =</span> <span class="fu">c</span>(<span class="st">"Intercepto"</span>, </span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Mujer &lt;br&gt; &lt;i&gt;(Ref. Hombre)&lt;/i&gt;"</span>,</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Educacion básica &lt;br&gt; &lt;i&gt;(Ref. Sin estudios)&lt;/i&gt;"</span>,</span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Educación media"</span>, </span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Educación superior"</span>,</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Postgrados"</span>,</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Nacionalidad extranjera &lt;br&gt; &lt;i&gt;(Ref. Nacionalidad chilena)&lt;/i&gt;"</span>,</span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Pertenece puablo originario &lt;br&gt; &lt;i&gt;(Ref. No pertenece pueblo originario)&lt;/i&gt;"</span>),</span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"Participacion en el mercado laboral"</span>,</span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption.above =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;color: #000000;border-top: 2px solid #000000;"&gt;
&lt;caption&gt;Participacion en el mercado laboral&lt;/caption&gt;
&lt;thead&gt;
&lt;tr&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 1&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 2&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 3&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 4&lt;/th&gt;
&lt;/tr&gt;
&lt;/thead&gt;
&lt;tbody&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Intercepto&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;4.85&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;5.16&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;5.16&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;5.16&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.02)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Mujer &lt;br&gt; &lt;i&gt;(Ref. Hombre)&lt;/i&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.06&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.04&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.03&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.03&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.04)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.04)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.04)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.04)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Educacion básica &lt;br&gt; &lt;i&gt;(Ref. Sin estudios)&lt;/i&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.69&lt;sup&gt;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.68&lt;sup&gt;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.68&lt;sup&gt;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Educación media&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.54&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.53&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.52&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Educación superior&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.10&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.10&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.09&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.33)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Postgrados&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.34&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.35&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.35&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.35)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.35)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.35)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Nacionalidad extranjera &lt;br&gt; &lt;i&gt;(Ref. Nacionalidad chilena)&lt;/i&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.12&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.12&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.07)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.07)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Pertenece puablo originario &lt;br&gt; &lt;i&gt;(Ref. No pertenece pueblo originario)&lt;/i&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.03&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.05)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.07&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.07&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.07&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Adj. R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.07&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.07&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.07&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-bottom: 2px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Num. obs.&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;3067&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;3067&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;3067&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;3067&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;tfoot&gt;
&lt;tr&gt;
&lt;td style="font-size: 0.8em;" colspan="5"&gt;*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05&lt;/td&gt;
&lt;/tr&gt;
&lt;/tfoot&gt;
&lt;/table&gt;</code></pre>
</div>
</div>
<p>sssssssssssssssssssss</p>

</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-neffaTrabajoCrisisModelos2020" class="csl-entry" role="listitem">
Neffa, Julio Cesar, and Enrique De La Garza Toledo, eds. 2020. <em>Trabajo y Crisis de Los Modelos Productivos En <span class="nocase">Am<span class="nocase">é</span>rica Latina</span></em>. Consejo Latinoamericano de Ciencias Sociales. CLACSO. <a href="https://doi.org/10.2307/j.ctv1gm02dh">https://doi.org/10.2307/j.ctv1gm02dh</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>